### ISSUE TITLE
Change log level

### ISSUE THREAD

**Issue by biscwii** [Bad-Pop/JCoinbase#13]
Salut !

Félicitations pour jcoinbase qui est très abouti.
Je me pose juste une question à propos des logs. En effet, sous Netbeans, la console est polluée par une multitude de log de niveau "INFO" à chaque action vers coinbase. J'ai essayé toutes les configurations possibles dans les options de Netbeans, et je voulais savoir si une option que je n'aurais pas vu aurait été codée dans jcoinbase pour éviter d'écrire des log si on ne le souhaitait pas.

Merci d'avance !

**Comment by biscwii** [comment]
Merci beaucoup pour ta réponse. Je vais sans doute travailler la dessus alors.
Juste une dernière question qui n'a rien à voir : Est ce que jcoinbase peut effectuer des transactions? Du type échanger des BTC vers USDT? etc.. Car je ne trouve pas d'infos dans la javadoc, où alors cela m'a échappé..

Merci encore ! :)

**Comment by Bad-Pop** [comment]
Hello @biscwii !
Désolé pour le temps de réponse.
Je n'ai à ce jour pas développé cette fonctionnalité dans JCoinbase, je me suis initialement concentré sur les basiques.

Encore une fois, si tu souhaites participer à l'évolution de JCoinbase, je t'invite à proposer la fonctionnalité comme pour les logs 😃 
Cela ne devrait pas être trop complexe, il faudra surtout lire la doc de coinbase et suivre la logique :)
